# -*- encoding: utf-8 -*-

=begin
#telegram-bot-api

#Unofficial telegram-bot-api OpenAPI spec. Generated from the Bot API docs at https://core.telegram.org/bots/api

The version of the OpenAPI document: Bot API 7.2

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "telegram-bot-openapi/version"

Gem::Specification.new do |s|
  s.name        = "telegram-bot-openapi"
  s.version     = TelegramBotOpenapi::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["OpenAPI-Generator"]
  s.email       = [""]
  s.homepage    = "https://openapi-generator.tech"
  s.summary     = "telegram-bot-api Ruby Gem"
  s.description = "Unofficial telegram-bot-api OpenAPI spec. Generated from the Bot API docs at https://core.telegram.org/bots/api"
  s.license     = "Unlicense"
  s.required_ruby_version = ">= 2.7"
  s.metadata    = { "github_repo" => "ssh://github.com/piiraa/telegram-bot-rb" }
  s.homepage = "https://github.com/piiraa/telegram-bot-rb"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
