=begin
#telegram-bot-api

#Unofficial telegram-bot-api OpenAPI spec. Generated from the Bot API docs at https://core.telegram.org/bots/api

The version of the OpenAPI document: Bot API 7.2

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'date'
require 'time'

module TelegramBotOpenapi
  # This object defines the criteria used to request a suitable chat. Information about the selected chat will be shared with the bot when the corresponding button is pressed. The bot will be granted requested rights in the chat if appropriate. More about requesting chats: https://core.telegram.org/bots/features#chat-and-user-selection.
  class KeyboardButtonRequestChat
    # Signed 32-bit identifier of the request, which will be received back in the ChatShared object. Must be unique within the message
    attr_accessor :request_id

    # Pass True to request a channel chat, pass False to request a group or a supergroup chat.
    attr_accessor :chat_is_channel

    # Optional. Pass True to request a forum supergroup, pass False to request a non-forum chat. If not specified, no additional restrictions are applied.
    attr_accessor :chat_is_forum

    # Optional. Pass True to request a supergroup or a channel with a username, pass False to request a chat without a username. If not specified, no additional restrictions are applied.
    attr_accessor :chat_has_username

    # Optional. Pass True to request a chat owned by the user. Otherwise, no additional restrictions are applied.
    attr_accessor :chat_is_created

    # Optional. A JSON-serialized object listing the required administrator rights of the user in the chat. The rights must be a superset of bot_administrator_rights. If not specified, no additional restrictions are applied.
    attr_accessor :user_administrator_rights

    # Optional. A JSON-serialized object listing the required administrator rights of the bot in the chat. The rights must be a subset of user_administrator_rights. If not specified, no additional restrictions are applied.
    attr_accessor :bot_administrator_rights

    # Optional. Pass True to request a chat with the bot as a member. Otherwise, no additional restrictions are applied.
    attr_accessor :bot_is_member

    # Optional. Pass True to request the chat's title
    attr_accessor :request_title

    # Optional. Pass True to request the chat's username
    attr_accessor :request_username

    # Optional. Pass True to request the chat's photo
    attr_accessor :request_photo

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'request_id' => :'request_id',
        :'chat_is_channel' => :'chat_is_channel',
        :'chat_is_forum' => :'chat_is_forum',
        :'chat_has_username' => :'chat_has_username',
        :'chat_is_created' => :'chat_is_created',
        :'user_administrator_rights' => :'user_administrator_rights',
        :'bot_administrator_rights' => :'bot_administrator_rights',
        :'bot_is_member' => :'bot_is_member',
        :'request_title' => :'request_title',
        :'request_username' => :'request_username',
        :'request_photo' => :'request_photo'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'request_id' => :'Integer',
        :'chat_is_channel' => :'Boolean',
        :'chat_is_forum' => :'Boolean',
        :'chat_has_username' => :'Boolean',
        :'chat_is_created' => :'Boolean',
        :'user_administrator_rights' => :'ChatAdministratorRights',
        :'bot_administrator_rights' => :'ChatAdministratorRights',
        :'bot_is_member' => :'Boolean',
        :'request_title' => :'Boolean',
        :'request_username' => :'Boolean',
        :'request_photo' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TelegramBotOpenapi::KeyboardButtonRequestChat` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TelegramBotOpenapi::KeyboardButtonRequestChat`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'request_id')
        self.request_id = attributes[:'request_id']
      else
        self.request_id = nil
      end

      if attributes.key?(:'chat_is_channel')
        self.chat_is_channel = attributes[:'chat_is_channel']
      else
        self.chat_is_channel = nil
      end

      if attributes.key?(:'chat_is_forum')
        self.chat_is_forum = attributes[:'chat_is_forum']
      end

      if attributes.key?(:'chat_has_username')
        self.chat_has_username = attributes[:'chat_has_username']
      end

      if attributes.key?(:'chat_is_created')
        self.chat_is_created = attributes[:'chat_is_created']
      end

      if attributes.key?(:'user_administrator_rights')
        self.user_administrator_rights = attributes[:'user_administrator_rights']
      end

      if attributes.key?(:'bot_administrator_rights')
        self.bot_administrator_rights = attributes[:'bot_administrator_rights']
      end

      if attributes.key?(:'bot_is_member')
        self.bot_is_member = attributes[:'bot_is_member']
      end

      if attributes.key?(:'request_title')
        self.request_title = attributes[:'request_title']
      end

      if attributes.key?(:'request_username')
        self.request_username = attributes[:'request_username']
      end

      if attributes.key?(:'request_photo')
        self.request_photo = attributes[:'request_photo']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @request_id.nil?
        invalid_properties.push('invalid value for "request_id", request_id cannot be nil.')
      end

      if @chat_is_channel.nil?
        invalid_properties.push('invalid value for "chat_is_channel", chat_is_channel cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @request_id.nil?
      return false if @chat_is_channel.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          request_id == o.request_id &&
          chat_is_channel == o.chat_is_channel &&
          chat_is_forum == o.chat_is_forum &&
          chat_has_username == o.chat_has_username &&
          chat_is_created == o.chat_is_created &&
          user_administrator_rights == o.user_administrator_rights &&
          bot_administrator_rights == o.bot_administrator_rights &&
          bot_is_member == o.bot_is_member &&
          request_title == o.request_title &&
          request_username == o.request_username &&
          request_photo == o.request_photo
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [request_id, chat_is_channel, chat_is_forum, chat_has_username, chat_is_created, user_administrator_rights, bot_administrator_rights, bot_is_member, request_title, request_username, request_photo].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = TelegramBotOpenapi.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
