=begin
#telegram-bot-api

#Unofficial telegram-bot-api OpenAPI spec. Generated from the Bot API docs at https://core.telegram.org/bots/api

The version of the OpenAPI document: Bot API 7.2

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'date'
require 'time'

module TelegramBotOpenapi
  # This object contains information about a poll.
  class Poll
    # Unique poll identifier
    attr_accessor :id

    # Poll question, 1-300 characters
    attr_accessor :question

    # List of poll options
    attr_accessor :options

    # Total number of users that voted in the poll
    attr_accessor :total_voter_count

    # True, if the poll is closed
    attr_accessor :is_closed

    # True, if the poll is anonymous
    attr_accessor :is_anonymous

    # Poll type, currently can be \"regular\" or \"quiz\"
    attr_accessor :type

    # True, if the poll allows multiple answers
    attr_accessor :allows_multiple_answers

    # Optional. 0-based identifier of the correct answer option. Available only for polls in the quiz mode, which are closed, or was sent (not forwarded) by the bot or to the private chat with the bot.
    attr_accessor :correct_option_id

    # Optional. Text that is shown when a user chooses an incorrect answer or taps on the lamp icon in a quiz-style poll, 0-200 characters
    attr_accessor :explanation

    # Optional. Special entities like usernames, URLs, bot commands, etc. that appear in the explanation
    attr_accessor :explanation_entities

    # Optional. Amount of time in seconds the poll will be active after creation
    attr_accessor :open_period

    # Optional. Point in time (Unix timestamp) when the poll will be automatically closed
    attr_accessor :close_date

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'question' => :'question',
        :'options' => :'options',
        :'total_voter_count' => :'total_voter_count',
        :'is_closed' => :'is_closed',
        :'is_anonymous' => :'is_anonymous',
        :'type' => :'type',
        :'allows_multiple_answers' => :'allows_multiple_answers',
        :'correct_option_id' => :'correct_option_id',
        :'explanation' => :'explanation',
        :'explanation_entities' => :'explanation_entities',
        :'open_period' => :'open_period',
        :'close_date' => :'close_date'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'question' => :'String',
        :'options' => :'Array<PollOption>',
        :'total_voter_count' => :'Integer',
        :'is_closed' => :'Boolean',
        :'is_anonymous' => :'Boolean',
        :'type' => :'String',
        :'allows_multiple_answers' => :'Boolean',
        :'correct_option_id' => :'Integer',
        :'explanation' => :'String',
        :'explanation_entities' => :'Array<MessageEntity>',
        :'open_period' => :'Integer',
        :'close_date' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TelegramBotOpenapi::Poll` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TelegramBotOpenapi::Poll`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'question')
        self.question = attributes[:'question']
      else
        self.question = nil
      end

      if attributes.key?(:'options')
        if (value = attributes[:'options']).is_a?(Array)
          self.options = value
        end
      else
        self.options = nil
      end

      if attributes.key?(:'total_voter_count')
        self.total_voter_count = attributes[:'total_voter_count']
      else
        self.total_voter_count = nil
      end

      if attributes.key?(:'is_closed')
        self.is_closed = attributes[:'is_closed']
      else
        self.is_closed = nil
      end

      if attributes.key?(:'is_anonymous')
        self.is_anonymous = attributes[:'is_anonymous']
      else
        self.is_anonymous = nil
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      else
        self.type = nil
      end

      if attributes.key?(:'allows_multiple_answers')
        self.allows_multiple_answers = attributes[:'allows_multiple_answers']
      else
        self.allows_multiple_answers = nil
      end

      if attributes.key?(:'correct_option_id')
        self.correct_option_id = attributes[:'correct_option_id']
      end

      if attributes.key?(:'explanation')
        self.explanation = attributes[:'explanation']
      end

      if attributes.key?(:'explanation_entities')
        if (value = attributes[:'explanation_entities']).is_a?(Array)
          self.explanation_entities = value
        end
      end

      if attributes.key?(:'open_period')
        self.open_period = attributes[:'open_period']
      end

      if attributes.key?(:'close_date')
        self.close_date = attributes[:'close_date']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @question.nil?
        invalid_properties.push('invalid value for "question", question cannot be nil.')
      end

      if @options.nil?
        invalid_properties.push('invalid value for "options", options cannot be nil.')
      end

      if @total_voter_count.nil?
        invalid_properties.push('invalid value for "total_voter_count", total_voter_count cannot be nil.')
      end

      if @is_closed.nil?
        invalid_properties.push('invalid value for "is_closed", is_closed cannot be nil.')
      end

      if @is_anonymous.nil?
        invalid_properties.push('invalid value for "is_anonymous", is_anonymous cannot be nil.')
      end

      if @type.nil?
        invalid_properties.push('invalid value for "type", type cannot be nil.')
      end

      if @allows_multiple_answers.nil?
        invalid_properties.push('invalid value for "allows_multiple_answers", allows_multiple_answers cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @question.nil?
      return false if @options.nil?
      return false if @total_voter_count.nil?
      return false if @is_closed.nil?
      return false if @is_anonymous.nil?
      return false if @type.nil?
      return false if @allows_multiple_answers.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          question == o.question &&
          options == o.options &&
          total_voter_count == o.total_voter_count &&
          is_closed == o.is_closed &&
          is_anonymous == o.is_anonymous &&
          type == o.type &&
          allows_multiple_answers == o.allows_multiple_answers &&
          correct_option_id == o.correct_option_id &&
          explanation == o.explanation &&
          explanation_entities == o.explanation_entities &&
          open_period == o.open_period &&
          close_date == o.close_date
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, question, options, total_voter_count, is_closed, is_anonymous, type, allows_multiple_answers, correct_option_id, explanation, explanation_entities, open_period, close_date].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = TelegramBotOpenapi.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
