=begin
#telegram-bot-api

#Unofficial telegram-bot-api OpenAPI spec. Generated from the Bot API docs at https://core.telegram.org/bots/api

The version of the OpenAPI document: Bot API 7.2

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'

# Unit tests for TelegramBotOpenapi::DefaultApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @api_instance = TelegramBotOpenapi::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@api_instance).to be_instance_of(TelegramBotOpenapi::DefaultApi)
    end
  end

  # unit tests for add_sticker_to_set
  # addStickerToSet
  # Use this method to add a new sticker to a set created by the bot. Emoji sticker sets can have up to 200 stickers. Other sticker sets can have up to 120 stickers. Returns True on success.
  # @param user_id 
  # @param name 
  # @param sticker 
  # @param [Hash] opts the optional parameters
  # @return [SetWebhook200Response]
  describe 'add_sticker_to_set test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for answer_callback_query
  # answerCallbackQuery
  # Use this method to send answers to callback queries sent from inline keyboards. The answer will be displayed to the user as a notification at the top of the chat screen or as an alert. On success, True is returned.
  # @param callback_query_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :text 
  # @option opts [Boolean] :show_alert 
  # @option opts [String] :url 
  # @option opts [Integer] :cache_time 
  # @return [SetWebhook200Response]
  describe 'answer_callback_query test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for answer_inline_query
  # answerInlineQuery
  # Use this method to send answers to an inline query. On success, True is returned. No more than 50 results per query are allowed.
  # @param inline_query_id 
  # @param results 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :cache_time 
  # @option opts [Boolean] :is_personal 
  # @option opts [String] :next_offset 
  # @option opts [InlineQueryResultsButton] :button 
  # @return [SetWebhook200Response]
  describe 'answer_inline_query test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for answer_pre_checkout_query
  # answerPreCheckoutQuery
  # Once the user has confirmed their payment and shipping details, the Bot API sends the final confirmation in the form of an Update with the field pre_checkout_query. Use this method to respond to such pre-checkout queries. On success, True is returned. Note: The Bot API must receive an answer within 10 seconds after the pre-checkout query was sent.
  # @param pre_checkout_query_id 
  # @param ok 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :error_message 
  # @return [SetWebhook200Response]
  describe 'answer_pre_checkout_query test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for answer_shipping_query
  # answerShippingQuery
  # If you sent an invoice requesting a shipping address and the parameter is_flexible was specified, the Bot API will send an Update with a shipping_query field to the bot. Use this method to reply to shipping queries. On success, True is returned.
  # @param shipping_query_id 
  # @param ok 
  # @param [Hash] opts the optional parameters
  # @option opts [Array<ShippingOption>] :shipping_options 
  # @option opts [String] :error_message 
  # @return [SetWebhook200Response]
  describe 'answer_shipping_query test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for answer_web_app_query
  # answerWebAppQuery
  # Use this method to set the result of an interaction with a Web App and send a corresponding message on behalf of the user to the chat from which the query originated. On success, a SentWebAppMessage object is returned.
  # @param web_app_query_id 
  # @param result 
  # @param [Hash] opts the optional parameters
  # @return [AnswerWebAppQuery200Response]
  describe 'answer_web_app_query test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for approve_chat_join_request
  # approveChatJoinRequest
  # Use this method to approve a chat join request. The bot must be an administrator in the chat for this to work and must have the can_invite_users administrator right. Returns True on success.
  # @param chat_id 
  # @param user_id 
  # @param [Hash] opts the optional parameters
  # @return [SetWebhook200Response]
  describe 'approve_chat_join_request test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for ban_chat_member
  # banChatMember
  # Use this method to ban a user in a group, a supergroup or a channel. In the case of supergroups and channels, the user will not be able to return to the chat on their own using invite links, etc., unless unbanned first. The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights. Returns True on success.
  # @param chat_id 
  # @param user_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :until_date 
  # @option opts [Boolean] :revoke_messages 
  # @return [SetWebhook200Response]
  describe 'ban_chat_member test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for ban_chat_sender_chat
  # banChatSenderChat
  # Use this method to ban a channel chat in a supergroup or a channel. Until the chat is unbanned, the owner of the banned chat won&#39;t be able to send messages on behalf of any of their channels. The bot must be an administrator in the supergroup or channel for this to work and must have the appropriate administrator rights. Returns True on success.
  # @param chat_id 
  # @param sender_chat_id 
  # @param [Hash] opts the optional parameters
  # @return [SetWebhook200Response]
  describe 'ban_chat_sender_chat test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for close
  # close
  # Use this method to close the bot instance before moving it from one local server to another. You need to delete the webhook before calling this method to ensure that the bot isn&#39;t launched again after server restart. The method will return error 429 in the first 10 minutes after the bot is launched. Returns True on success. Requires no parameters.
  # @param [Hash] opts the optional parameters
  # @return [SetWebhook200Response]
  describe 'close test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for close_forum_topic
  # closeForumTopic
  # Use this method to close an open topic in a forum supergroup chat. The bot must be an administrator in the chat for this to work and must have the can_manage_topics administrator rights, unless it is the creator of the topic. Returns True on success.
  # @param chat_id 
  # @param message_thread_id 
  # @param [Hash] opts the optional parameters
  # @return [SetWebhook200Response]
  describe 'close_forum_topic test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for close_general_forum_topic
  # closeGeneralForumTopic
  # Use this method to close an open &#39;General&#39; topic in a forum supergroup chat. The bot must be an administrator in the chat for this to work and must have the can_manage_topics administrator rights. Returns True on success.
  # @param chat_id 
  # @param [Hash] opts the optional parameters
  # @return [SetWebhook200Response]
  describe 'close_general_forum_topic test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for copy_message
  # copyMessage
  # Use this method to copy messages of any kind. Service messages, giveaway messages, giveaway winners messages, and invoice messages can&#39;t be copied. A quiz poll can be copied only if the value of the field correct_option_id is known to the bot. The method is analogous to the method forwardMessage, but the copied message doesn&#39;t have a link to the original message. Returns the MessageId of the sent message on success.
  # @param chat_id 
  # @param from_chat_id 
  # @param message_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :message_thread_id 
  # @option opts [String] :caption 
  # @option opts [String] :parse_mode 
  # @option opts [Array<MessageEntity>] :caption_entities 
  # @option opts [Boolean] :disable_notification 
  # @option opts [Boolean] :protect_content 
  # @option opts [ReplyParameters] :reply_parameters 
  # @option opts [Hash<String, SendMessageReplyMarkupParameterValue>] :reply_markup 
  # @return [CopyMessage200Response]
  describe 'copy_message test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for copy_messages
  # copyMessages
  # Use this method to copy messages of any kind. If some of the specified messages can&#39;t be found or copied, they are skipped. Service messages, giveaway messages, giveaway winners messages, and invoice messages can&#39;t be copied. A quiz poll can be copied only if the value of the field correct_option_id is known to the bot. The method is analogous to the method forwardMessages, but the copied messages don&#39;t have a link to the original message. Album grouping is kept for copied messages. On success, an array of MessageId of the sent messages is returned.
  # @param chat_id 
  # @param from_chat_id 
  # @param message_ids 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :message_thread_id 
  # @option opts [Boolean] :disable_notification 
  # @option opts [Boolean] :protect_content 
  # @option opts [Boolean] :remove_caption 
  # @return [ForwardMessages200Response]
  describe 'copy_messages test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_chat_invite_link
  # createChatInviteLink
  # Use this method to create an additional invite link for a chat. The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights. The link can be revoked using the method revokeChatInviteLink. Returns the new invite link as ChatInviteLink object.
  # @param chat_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :name 
  # @option opts [Integer] :expire_date 
  # @option opts [Integer] :member_limit 
  # @option opts [Boolean] :creates_join_request 
  # @return [CreateChatInviteLink200Response]
  describe 'create_chat_invite_link test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_forum_topic
  # createForumTopic
  # Use this method to create a topic in a forum supergroup chat. The bot must be an administrator in the chat for this to work and must have the can_manage_topics administrator rights. Returns information about the created topic as a ForumTopic object.
  # @param chat_id 
  # @param name 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :icon_color 
  # @option opts [String] :icon_custom_emoji_id 
  # @return [CreateForumTopic200Response]
  describe 'create_forum_topic test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_invoice_link
  # createInvoiceLink
  # Use this method to create a link for an invoice. Returns the created invoice link as String on success.
  # @param title 
  # @param description 
  # @param payload 
  # @param provider_token 
  # @param currency 
  # @param prices 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :max_tip_amount 
  # @option opts [Array<Integer>] :suggested_tip_amounts 
  # @option opts [String] :provider_data 
  # @option opts [String] :photo_url 
  # @option opts [Integer] :photo_size 
  # @option opts [Integer] :photo_width 
  # @option opts [Integer] :photo_height 
  # @option opts [Boolean] :need_name 
  # @option opts [Boolean] :need_phone_number 
  # @option opts [Boolean] :need_email 
  # @option opts [Boolean] :need_shipping_address 
  # @option opts [Boolean] :send_phone_number_to_provider 
  # @option opts [Boolean] :send_email_to_provider 
  # @option opts [Boolean] :is_flexible 
  # @return [ExportChatInviteLink200Response]
  describe 'create_invoice_link test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_new_sticker_set
  # createNewStickerSet
  # Use this method to create a new sticker set owned by a user. The bot will be able to edit the sticker set thus created. Returns True on success.
  # @param user_id 
  # @param name 
  # @param title 
  # @param stickers 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sticker_type 
  # @option opts [Boolean] :needs_repainting 
  # @return [SetWebhook200Response]
  describe 'create_new_sticker_set test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for decline_chat_join_request
  # declineChatJoinRequest
  # Use this method to decline a chat join request. The bot must be an administrator in the chat for this to work and must have the can_invite_users administrator right. Returns True on success.
  # @param chat_id 
  # @param user_id 
  # @param [Hash] opts the optional parameters
  # @return [SetWebhook200Response]
  describe 'decline_chat_join_request test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_chat_photo
  # deleteChatPhoto
  # Use this method to delete a chat photo. Photos can&#39;t be changed for private chats. The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights. Returns True on success.
  # @param chat_id 
  # @param [Hash] opts the optional parameters
  # @return [SetWebhook200Response]
  describe 'delete_chat_photo test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_chat_sticker_set
  # deleteChatStickerSet
  # Use this method to delete a group sticker set from a supergroup. The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights. Use the field can_set_sticker_set optionally returned in getChat requests to check if the bot can use this method. Returns True on success.
  # @param chat_id 
  # @param [Hash] opts the optional parameters
  # @return [SetWebhook200Response]
  describe 'delete_chat_sticker_set test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_forum_topic
  # deleteForumTopic
  # Use this method to delete a forum topic along with all its messages in a forum supergroup chat. The bot must be an administrator in the chat for this to work and must have the can_delete_messages administrator rights. Returns True on success.
  # @param chat_id 
  # @param message_thread_id 
  # @param [Hash] opts the optional parameters
  # @return [SetWebhook200Response]
  describe 'delete_forum_topic test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_message
  # deleteMessage
  # Use this method to delete a message, including service messages, with the following limitations: - A message can only be deleted if it was sent less than 48 hours ago. - Service messages about a supergroup, channel, or forum topic creation can&#39;t be deleted. - A dice message in a private chat can only be deleted if it was sent more than 24 hours ago. - Bots can delete outgoing messages in private chats, groups, and supergroups. - Bots can delete incoming messages in private chats. - Bots granted can_post_messages permissions can delete outgoing messages in channels. - If the bot is an administrator of a group, it can delete any message there. - If the bot has can_delete_messages permission in a supergroup or a channel, it can delete any message there. Returns True on success.
  # @param chat_id 
  # @param message_id 
  # @param [Hash] opts the optional parameters
  # @return [SetWebhook200Response]
  describe 'delete_message test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_messages
  # deleteMessages
  # Use this method to delete multiple messages simultaneously. If some of the specified messages can&#39;t be found, they are skipped. Returns True on success.
  # @param chat_id 
  # @param message_ids 
  # @param [Hash] opts the optional parameters
  # @return [SetWebhook200Response]
  describe 'delete_messages test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_my_commands
  # deleteMyCommands
  # Use this method to delete the list of the bot&#39;s commands for the given scope and user language. After deletion, higher level commands will be shown to affected users. Returns True on success.
  # @param [Hash] opts the optional parameters
  # @option opts [Object] :scope 
  # @option opts [String] :language_code 
  # @return [SetWebhook200Response]
  describe 'delete_my_commands test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_sticker_from_set
  # deleteStickerFromSet
  # Use this method to delete a sticker from a set created by the bot. Returns True on success.
  # @param sticker 
  # @param [Hash] opts the optional parameters
  # @return [SetWebhook200Response]
  describe 'delete_sticker_from_set test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_sticker_set
  # deleteStickerSet
  # Use this method to delete a sticker set that was created by the bot. Returns True on success.
  # @param name 
  # @param [Hash] opts the optional parameters
  # @return [SetWebhook200Response]
  describe 'delete_sticker_set test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_webhook
  # deleteWebhook
  # Use this method to remove webhook integration if you decide to switch back to getUpdates. Returns True on success.
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :drop_pending_updates 
  # @return [SetWebhook200Response]
  describe 'delete_webhook test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for edit_chat_invite_link
  # editChatInviteLink
  # Use this method to edit a non-primary invite link created by the bot. The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights. Returns the edited invite link as a ChatInviteLink object.
  # @param chat_id 
  # @param invite_link 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :name 
  # @option opts [Integer] :expire_date 
  # @option opts [Integer] :member_limit 
  # @option opts [Boolean] :creates_join_request 
  # @return [CreateChatInviteLink200Response]
  describe 'edit_chat_invite_link test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for edit_forum_topic
  # editForumTopic
  # Use this method to edit name and icon of a topic in a forum supergroup chat. The bot must be an administrator in the chat for this to work and must have can_manage_topics administrator rights, unless it is the creator of the topic. Returns True on success.
  # @param chat_id 
  # @param message_thread_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :name 
  # @option opts [String] :icon_custom_emoji_id 
  # @return [SetWebhook200Response]
  describe 'edit_forum_topic test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for edit_general_forum_topic
  # editGeneralForumTopic
  # Use this method to edit the name of the &#39;General&#39; topic in a forum supergroup chat. The bot must be an administrator in the chat for this to work and must have can_manage_topics administrator rights. Returns True on success.
  # @param chat_id 
  # @param name 
  # @param [Hash] opts the optional parameters
  # @return [SetWebhook200Response]
  describe 'edit_general_forum_topic test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for edit_message_caption
  # editMessageCaption
  # Use this method to edit captions of messages. On success, if the edited message is not an inline message, the edited Message is returned, otherwise True is returned.
  # @param [Hash] opts the optional parameters
  # @option opts [Hash<String, SendMessageChatIdParameterValue>] :chat_id 
  # @option opts [Integer] :message_id 
  # @option opts [String] :inline_message_id 
  # @option opts [String] :caption 
  # @option opts [String] :parse_mode 
  # @option opts [Array<MessageEntity>] :caption_entities 
  # @option opts [InlineKeyboardMarkup] :reply_markup 
  # @return [EditMessageText200Response]
  describe 'edit_message_caption test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for edit_message_live_location
  # editMessageLiveLocation
  # Use this method to edit live location messages. A location can be edited until its live_period expires or editing is explicitly disabled by a call to stopMessageLiveLocation. On success, if the edited message is not an inline message, the edited Message is returned, otherwise True is returned.
  # @param latitude 
  # @param longitude 
  # @param [Hash] opts the optional parameters
  # @option opts [Hash<String, SendMessageChatIdParameterValue>] :chat_id 
  # @option opts [Integer] :message_id 
  # @option opts [String] :inline_message_id 
  # @option opts [Float] :horizontal_accuracy 
  # @option opts [Integer] :heading 
  # @option opts [Integer] :proximity_alert_radius 
  # @option opts [InlineKeyboardMarkup] :reply_markup 
  # @return [EditMessageText200Response]
  describe 'edit_message_live_location test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for edit_message_media
  # editMessageMedia
  # Use this method to edit animation, audio, document, photo, or video messages. If a message is part of a message album, then it can be edited only to an audio for audio albums, only to a document for document albums and to a photo or a video otherwise. When an inline message is edited, a new file can&#39;t be uploaded; use a previously uploaded file via its file_id or specify a URL. On success, if the edited message is not an inline message, the edited Message is returned, otherwise True is returned.
  # @param media 
  # @param [Hash] opts the optional parameters
  # @option opts [Hash<String, SendMessageChatIdParameterValue>] :chat_id 
  # @option opts [Integer] :message_id 
  # @option opts [String] :inline_message_id 
  # @option opts [InlineKeyboardMarkup] :reply_markup 
  # @return [EditMessageText200Response]
  describe 'edit_message_media test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for edit_message_reply_markup
  # editMessageReplyMarkup
  # Use this method to edit only the reply markup of messages. On success, if the edited message is not an inline message, the edited Message is returned, otherwise True is returned.
  # @param [Hash] opts the optional parameters
  # @option opts [Hash<String, SendMessageChatIdParameterValue>] :chat_id 
  # @option opts [Integer] :message_id 
  # @option opts [String] :inline_message_id 
  # @option opts [InlineKeyboardMarkup] :reply_markup 
  # @return [EditMessageText200Response]
  describe 'edit_message_reply_markup test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for edit_message_text
  # editMessageText
  # Use this method to edit text and game messages. On success, if the edited message is not an inline message, the edited Message is returned, otherwise True is returned.
  # @param text 
  # @param [Hash] opts the optional parameters
  # @option opts [Hash<String, SendMessageChatIdParameterValue>] :chat_id 
  # @option opts [Integer] :message_id 
  # @option opts [String] :inline_message_id 
  # @option opts [String] :parse_mode 
  # @option opts [Array<MessageEntity>] :entities 
  # @option opts [LinkPreviewOptions] :link_preview_options 
  # @option opts [InlineKeyboardMarkup] :reply_markup 
  # @return [EditMessageText200Response]
  describe 'edit_message_text test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for export_chat_invite_link
  # exportChatInviteLink
  # Use this method to generate a new primary invite link for a chat; any previously generated primary link is revoked. The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights. Returns the new invite link as String on success.
  # @param chat_id 
  # @param [Hash] opts the optional parameters
  # @return [ExportChatInviteLink200Response]
  describe 'export_chat_invite_link test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for forward_message
  # forwardMessage
  # Use this method to forward messages of any kind. Service messages and messages with protected content can&#39;t be forwarded. On success, the sent Message is returned.
  # @param chat_id 
  # @param from_chat_id 
  # @param message_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :message_thread_id 
  # @option opts [Boolean] :disable_notification 
  # @option opts [Boolean] :protect_content 
  # @return [SendMessage200Response]
  describe 'forward_message test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for forward_messages
  # forwardMessages
  # Use this method to forward multiple messages of any kind. If some of the specified messages can&#39;t be found or forwarded, they are skipped. Service messages and messages with protected content can&#39;t be forwarded. Album grouping is kept for forwarded messages. On success, an array of MessageId of the sent messages is returned.
  # @param chat_id 
  # @param from_chat_id 
  # @param message_ids 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :message_thread_id 
  # @option opts [Boolean] :disable_notification 
  # @option opts [Boolean] :protect_content 
  # @return [ForwardMessages200Response]
  describe 'forward_messages test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_business_connection
  # getBusinessConnection
  # Use this method to get information about the connection of the bot with a business account. Returns a BusinessConnection object on success.
  # @param business_connection_id 
  # @param [Hash] opts the optional parameters
  # @return [GetBusinessConnection200Response]
  describe 'get_business_connection test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_chat
  # getChat
  # Use this method to get up to date information about the chat. Returns a Chat object on success.
  # @param chat_id 
  # @param [Hash] opts the optional parameters
  # @return [GetChat200Response]
  describe 'get_chat test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_chat_administrators
  # getChatAdministrators
  # Use this method to get a list of administrators in a chat, which aren&#39;t bots. Returns an Array of ChatMember objects.
  # @param chat_id 
  # @param [Hash] opts the optional parameters
  # @return [GetChatAdministrators200Response]
  describe 'get_chat_administrators test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_chat_member
  # getChatMember
  # Use this method to get information about a member of a chat. The method is only guaranteed to work for other users if the bot is an administrator in the chat. Returns a ChatMember object on success.
  # @param chat_id 
  # @param user_id 
  # @param [Hash] opts the optional parameters
  # @return [GetChatMember200Response]
  describe 'get_chat_member test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_chat_member_count
  # getChatMemberCount
  # Use this method to get the number of members in a chat. Returns Int on success.
  # @param chat_id 
  # @param [Hash] opts the optional parameters
  # @return [GetChatMemberCount200Response]
  describe 'get_chat_member_count test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_chat_menu_button
  # getChatMenuButton
  # Use this method to get the current value of the bot&#39;s menu button in a private chat, or the default menu button. Returns MenuButton on success.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :chat_id 
  # @return [GetChatMenuButton200Response]
  describe 'get_chat_menu_button test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_custom_emoji_stickers
  # getCustomEmojiStickers
  # Use this method to get information about custom emoji stickers by their identifiers. Returns an Array of Sticker objects.
  # @param custom_emoji_ids 
  # @param [Hash] opts the optional parameters
  # @return [GetForumTopicIconStickers200Response]
  describe 'get_custom_emoji_stickers test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_file
  # getFile
  # Use this method to get basic information about a file and prepare it for downloading. For the moment, bots can download files of up to 20MB in size. On success, a File object is returned. The file can then be downloaded via the link https://api.telegram.org/file/bot&lt;token&gt;/&lt;file_path&gt;, where &lt;file_path&gt; is taken from the response. It is guaranteed that the link will be valid for at least 1 hour. When the link expires, a new one can be requested by calling getFile again. Note: This function may not preserve the original file name and MIME type. You should save the file&#39;s MIME type and name (if available) when the File object is received.
  # @param file_id 
  # @param [Hash] opts the optional parameters
  # @return [GetFile200Response]
  describe 'get_file test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_forum_topic_icon_stickers
  # getForumTopicIconStickers
  # Use this method to get custom emoji stickers, which can be used as a forum topic icon by any user. Requires no parameters. Returns an Array of Sticker objects.
  # @param [Hash] opts the optional parameters
  # @return [GetForumTopicIconStickers200Response]
  describe 'get_forum_topic_icon_stickers test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_game_high_scores
  # getGameHighScores
  # Use this method to get data for high score tables. Will return the score of the specified user and several of their neighbors in a game. Returns an Array of GameHighScore objects.
  # @param user_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :chat_id 
  # @option opts [Integer] :message_id 
  # @option opts [String] :inline_message_id 
  # @return [GetGameHighScores200Response]
  describe 'get_game_high_scores test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_me
  # getMe
  # A simple method for testing your bot&#39;s authentication token. Requires no parameters. Returns basic information about the bot in form of a User object.
  # @param [Hash] opts the optional parameters
  # @return [GetMe200Response]
  describe 'get_me test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_my_commands
  # getMyCommands
  # Use this method to get the current list of the bot&#39;s commands for the given scope and user language. Returns an Array of BotCommand objects. If commands aren&#39;t set, an empty list is returned.
  # @param [Hash] opts the optional parameters
  # @option opts [Object] :scope 
  # @option opts [String] :language_code 
  # @return [GetMyCommands200Response]
  describe 'get_my_commands test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_my_default_administrator_rights
  # getMyDefaultAdministratorRights
  # Use this method to get the current default administrator rights of the bot. Returns ChatAdministratorRights on success.
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :for_channels 
  # @return [GetMyDefaultAdministratorRights200Response]
  describe 'get_my_default_administrator_rights test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_my_description
  # getMyDescription
  # Use this method to get the current bot description for the given user language. Returns BotDescription on success.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :language_code 
  # @return [GetMyDescription200Response]
  describe 'get_my_description test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_my_name
  # getMyName
  # Use this method to get the current bot name for the given user language. Returns BotName on success.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :language_code 
  # @return [GetMyName200Response]
  describe 'get_my_name test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_my_short_description
  # getMyShortDescription
  # Use this method to get the current bot short description for the given user language. Returns BotShortDescription on success.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :language_code 
  # @return [GetMyShortDescription200Response]
  describe 'get_my_short_description test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_sticker_set
  # getStickerSet
  # Use this method to get a sticker set. On success, a StickerSet object is returned.
  # @param name 
  # @param [Hash] opts the optional parameters
  # @return [GetStickerSet200Response]
  describe 'get_sticker_set test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_updates
  # getUpdates
  # Use this method to receive incoming updates using long polling (wiki). Returns an Array of Update objects.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :offset 
  # @option opts [Integer] :limit 
  # @option opts [Integer] :timeout 
  # @option opts [Array<String>] :allowed_updates 
  # @return [GetUpdates200Response]
  describe 'get_updates test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_user_chat_boosts
  # getUserChatBoosts
  # Use this method to get the list of boosts added to a chat by a user. Requires administrator rights in the chat. Returns a UserChatBoosts object.
  # @param chat_id 
  # @param user_id 
  # @param [Hash] opts the optional parameters
  # @return [GetUserChatBoosts200Response]
  describe 'get_user_chat_boosts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_user_profile_photos
  # getUserProfilePhotos
  # Use this method to get a list of profile pictures for a user. Returns a UserProfilePhotos object.
  # @param user_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :offset 
  # @option opts [Integer] :limit 
  # @return [GetUserProfilePhotos200Response]
  describe 'get_user_profile_photos test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_webhook_info
  # getWebhookInfo
  # Use this method to get current webhook status. Requires no parameters. On success, returns a WebhookInfo object. If the bot is using getUpdates, will return an object with the url field empty.
  # @param [Hash] opts the optional parameters
  # @return [GetWebhookInfo200Response]
  describe 'get_webhook_info test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for hide_general_forum_topic
  # hideGeneralForumTopic
  # Use this method to hide the &#39;General&#39; topic in a forum supergroup chat. The bot must be an administrator in the chat for this to work and must have the can_manage_topics administrator rights. The topic will be automatically closed if it was open. Returns True on success.
  # @param chat_id 
  # @param [Hash] opts the optional parameters
  # @return [SetWebhook200Response]
  describe 'hide_general_forum_topic test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for leave_chat
  # leaveChat
  # Use this method for your bot to leave a group, supergroup or channel. Returns True on success.
  # @param chat_id 
  # @param [Hash] opts the optional parameters
  # @return [SetWebhook200Response]
  describe 'leave_chat test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for log_out
  # logOut
  # Use this method to log out from the cloud Bot API server before launching the bot locally. You must log out the bot before running it locally, otherwise there is no guarantee that the bot will receive updates. After a successful call, you can immediately log in on a local server, but will not be able to log in back to the cloud Bot API server for 10 minutes. Returns True on success. Requires no parameters.
  # @param [Hash] opts the optional parameters
  # @return [SetWebhook200Response]
  describe 'log_out test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for pin_chat_message
  # pinChatMessage
  # Use this method to add a message to the list of pinned messages in a chat. If the chat is not a private chat, the bot must be an administrator in the chat for this to work and must have the &#39;can_pin_messages&#39; administrator right in a supergroup or &#39;can_edit_messages&#39; administrator right in a channel. Returns True on success.
  # @param chat_id 
  # @param message_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :disable_notification 
  # @return [SetWebhook200Response]
  describe 'pin_chat_message test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for promote_chat_member
  # promoteChatMember
  # Use this method to promote or demote a user in a supergroup or a channel. The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights. Pass False for all boolean parameters to demote a user. Returns True on success.
  # @param chat_id 
  # @param user_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :is_anonymous 
  # @option opts [Boolean] :can_manage_chat 
  # @option opts [Boolean] :can_delete_messages 
  # @option opts [Boolean] :can_manage_video_chats 
  # @option opts [Boolean] :can_restrict_members 
  # @option opts [Boolean] :can_promote_members 
  # @option opts [Boolean] :can_change_info 
  # @option opts [Boolean] :can_invite_users 
  # @option opts [Boolean] :can_post_stories 
  # @option opts [Boolean] :can_edit_stories 
  # @option opts [Boolean] :can_delete_stories 
  # @option opts [Boolean] :can_post_messages 
  # @option opts [Boolean] :can_edit_messages 
  # @option opts [Boolean] :can_pin_messages 
  # @option opts [Boolean] :can_manage_topics 
  # @return [SetWebhook200Response]
  describe 'promote_chat_member test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reopen_forum_topic
  # reopenForumTopic
  # Use this method to reopen a closed topic in a forum supergroup chat. The bot must be an administrator in the chat for this to work and must have the can_manage_topics administrator rights, unless it is the creator of the topic. Returns True on success.
  # @param chat_id 
  # @param message_thread_id 
  # @param [Hash] opts the optional parameters
  # @return [SetWebhook200Response]
  describe 'reopen_forum_topic test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reopen_general_forum_topic
  # reopenGeneralForumTopic
  # Use this method to reopen a closed &#39;General&#39; topic in a forum supergroup chat. The bot must be an administrator in the chat for this to work and must have the can_manage_topics administrator rights. The topic will be automatically unhidden if it was hidden. Returns True on success.
  # @param chat_id 
  # @param [Hash] opts the optional parameters
  # @return [SetWebhook200Response]
  describe 'reopen_general_forum_topic test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for replace_sticker_in_set
  # replaceStickerInSet
  # Use this method to replace an existing sticker in a sticker set with a new one. The method is equivalent to calling deleteStickerFromSet, then addStickerToSet, then setStickerPositionInSet. Returns True on success.
  # @param user_id 
  # @param name 
  # @param old_sticker 
  # @param sticker 
  # @param [Hash] opts the optional parameters
  # @return [SetWebhook200Response]
  describe 'replace_sticker_in_set test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for restrict_chat_member
  # restrictChatMember
  # Use this method to restrict a user in a supergroup. The bot must be an administrator in the supergroup for this to work and must have the appropriate administrator rights. Pass True for all permissions to lift restrictions from a user. Returns True on success.
  # @param chat_id 
  # @param user_id 
  # @param permissions 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :use_independent_chat_permissions 
  # @option opts [Integer] :until_date 
  # @return [SetWebhook200Response]
  describe 'restrict_chat_member test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for revoke_chat_invite_link
  # revokeChatInviteLink
  # Use this method to revoke an invite link created by the bot. If the primary link is revoked, a new link is automatically generated. The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights. Returns the revoked invite link as ChatInviteLink object.
  # @param chat_id 
  # @param invite_link 
  # @param [Hash] opts the optional parameters
  # @return [CreateChatInviteLink200Response]
  describe 'revoke_chat_invite_link test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for send_animation
  # sendAnimation
  # Use this method to send animation files (GIF or H.264/MPEG-4 AVC video without sound). On success, the sent Message is returned. Bots can currently send animation files of up to 50 MB in size, this limit may be changed in the future.
  # @param chat_id 
  # @param animation 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :business_connection_id 
  # @option opts [Integer] :message_thread_id 
  # @option opts [Integer] :duration 
  # @option opts [Integer] :width 
  # @option opts [Integer] :height 
  # @option opts [Hash<String, SendPhotoPhotoParameterValue>] :thumbnail 
  # @option opts [String] :caption 
  # @option opts [String] :parse_mode 
  # @option opts [Array<MessageEntity>] :caption_entities 
  # @option opts [Boolean] :has_spoiler 
  # @option opts [Boolean] :disable_notification 
  # @option opts [Boolean] :protect_content 
  # @option opts [ReplyParameters] :reply_parameters 
  # @option opts [Hash<String, SendMessageReplyMarkupParameterValue>] :reply_markup 
  # @return [SendMessage200Response]
  describe 'send_animation test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for send_audio
  # sendAudio
  # Use this method to send audio files, if you want Telegram clients to display them in the music player. Your audio must be in the .MP3 or .M4A format. On success, the sent Message is returned. Bots can currently send audio files of up to 50 MB in size, this limit may be changed in the future. For sending voice messages, use the sendVoice method instead.
  # @param chat_id 
  # @param audio 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :business_connection_id 
  # @option opts [Integer] :message_thread_id 
  # @option opts [String] :caption 
  # @option opts [String] :parse_mode 
  # @option opts [Array<MessageEntity>] :caption_entities 
  # @option opts [Integer] :duration 
  # @option opts [String] :performer 
  # @option opts [String] :title 
  # @option opts [Hash<String, SendPhotoPhotoParameterValue>] :thumbnail 
  # @option opts [Boolean] :disable_notification 
  # @option opts [Boolean] :protect_content 
  # @option opts [ReplyParameters] :reply_parameters 
  # @option opts [Hash<String, SendMessageReplyMarkupParameterValue>] :reply_markup 
  # @return [SendMessage200Response]
  describe 'send_audio test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for send_chat_action
  # sendChatAction
  # Use this method when you need to tell the user that something is happening on the bot&#39;s side. The status is set for 5 seconds or less (when a message arrives from your bot, Telegram clients clear its typing status). Returns True on success. We only recommend using this method when a response from the bot will take a noticeable amount of time to arrive.
  # @param chat_id 
  # @param action 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :business_connection_id 
  # @option opts [Integer] :message_thread_id 
  # @return [SetWebhook200Response]
  describe 'send_chat_action test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for send_contact
  # sendContact
  # Use this method to send phone contacts. On success, the sent Message is returned.
  # @param chat_id 
  # @param phone_number 
  # @param first_name 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :business_connection_id 
  # @option opts [Integer] :message_thread_id 
  # @option opts [String] :last_name 
  # @option opts [String] :vcard 
  # @option opts [Boolean] :disable_notification 
  # @option opts [Boolean] :protect_content 
  # @option opts [ReplyParameters] :reply_parameters 
  # @option opts [Hash<String, SendMessageReplyMarkupParameterValue>] :reply_markup 
  # @return [SendMessage200Response]
  describe 'send_contact test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for send_dice
  # sendDice
  # Use this method to send an animated emoji that will display a random value. On success, the sent Message is returned.
  # @param chat_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :business_connection_id 
  # @option opts [Integer] :message_thread_id 
  # @option opts [String] :emoji 
  # @option opts [Boolean] :disable_notification 
  # @option opts [Boolean] :protect_content 
  # @option opts [ReplyParameters] :reply_parameters 
  # @option opts [Hash<String, SendMessageReplyMarkupParameterValue>] :reply_markup 
  # @return [SendMessage200Response]
  describe 'send_dice test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for send_document
  # sendDocument
  # Use this method to send general files. On success, the sent Message is returned. Bots can currently send files of any type of up to 50 MB in size, this limit may be changed in the future.
  # @param chat_id 
  # @param document 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :business_connection_id 
  # @option opts [Integer] :message_thread_id 
  # @option opts [Hash<String, SendPhotoPhotoParameterValue>] :thumbnail 
  # @option opts [String] :caption 
  # @option opts [String] :parse_mode 
  # @option opts [Array<MessageEntity>] :caption_entities 
  # @option opts [Boolean] :disable_content_type_detection 
  # @option opts [Boolean] :disable_notification 
  # @option opts [Boolean] :protect_content 
  # @option opts [ReplyParameters] :reply_parameters 
  # @option opts [Hash<String, SendMessageReplyMarkupParameterValue>] :reply_markup 
  # @return [SendMessage200Response]
  describe 'send_document test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for send_game
  # sendGame
  # Use this method to send a game. On success, the sent Message is returned.
  # @param chat_id 
  # @param game_short_name 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :business_connection_id 
  # @option opts [Integer] :message_thread_id 
  # @option opts [Boolean] :disable_notification 
  # @option opts [Boolean] :protect_content 
  # @option opts [ReplyParameters] :reply_parameters 
  # @option opts [InlineKeyboardMarkup] :reply_markup 
  # @return [SendMessage200Response]
  describe 'send_game test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for send_invoice
  # sendInvoice
  # Use this method to send invoices. On success, the sent Message is returned.
  # @param chat_id 
  # @param title 
  # @param description 
  # @param payload 
  # @param provider_token 
  # @param currency 
  # @param prices 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :message_thread_id 
  # @option opts [Integer] :max_tip_amount 
  # @option opts [Array<Integer>] :suggested_tip_amounts 
  # @option opts [String] :start_parameter 
  # @option opts [String] :provider_data 
  # @option opts [String] :photo_url 
  # @option opts [Integer] :photo_size 
  # @option opts [Integer] :photo_width 
  # @option opts [Integer] :photo_height 
  # @option opts [Boolean] :need_name 
  # @option opts [Boolean] :need_phone_number 
  # @option opts [Boolean] :need_email 
  # @option opts [Boolean] :need_shipping_address 
  # @option opts [Boolean] :send_phone_number_to_provider 
  # @option opts [Boolean] :send_email_to_provider 
  # @option opts [Boolean] :is_flexible 
  # @option opts [Boolean] :disable_notification 
  # @option opts [Boolean] :protect_content 
  # @option opts [ReplyParameters] :reply_parameters 
  # @option opts [InlineKeyboardMarkup] :reply_markup 
  # @return [SendMessage200Response]
  describe 'send_invoice test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for send_location
  # sendLocation
  # Use this method to send point on the map. On success, the sent Message is returned.
  # @param chat_id 
  # @param latitude 
  # @param longitude 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :business_connection_id 
  # @option opts [Integer] :message_thread_id 
  # @option opts [Float] :horizontal_accuracy 
  # @option opts [Integer] :live_period 
  # @option opts [Integer] :heading 
  # @option opts [Integer] :proximity_alert_radius 
  # @option opts [Boolean] :disable_notification 
  # @option opts [Boolean] :protect_content 
  # @option opts [ReplyParameters] :reply_parameters 
  # @option opts [Hash<String, SendMessageReplyMarkupParameterValue>] :reply_markup 
  # @return [SendMessage200Response]
  describe 'send_location test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for send_media_group
  # sendMediaGroup
  # Use this method to send a group of photos, videos, documents or audios as an album. Documents and audio files can be only grouped in an album with messages of the same type. On success, an array of Messages that were sent is returned.
  # @param chat_id 
  # @param media 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :business_connection_id 
  # @option opts [Integer] :message_thread_id 
  # @option opts [Boolean] :disable_notification 
  # @option opts [Boolean] :protect_content 
  # @option opts [ReplyParameters] :reply_parameters 
  # @return [SendMediaGroup200Response]
  describe 'send_media_group test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for send_message
  # sendMessage
  # Use this method to send text messages. On success, the sent Message is returned.
  # @param chat_id 
  # @param text 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :business_connection_id 
  # @option opts [Integer] :message_thread_id 
  # @option opts [String] :parse_mode 
  # @option opts [Array<MessageEntity>] :entities 
  # @option opts [LinkPreviewOptions] :link_preview_options 
  # @option opts [Boolean] :disable_notification 
  # @option opts [Boolean] :protect_content 
  # @option opts [ReplyParameters] :reply_parameters 
  # @option opts [Hash<String, SendMessageReplyMarkupParameterValue>] :reply_markup 
  # @return [SendMessage200Response]
  describe 'send_message test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for send_photo
  # sendPhoto
  # Use this method to send photos. On success, the sent Message is returned.
  # @param chat_id 
  # @param photo 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :business_connection_id 
  # @option opts [Integer] :message_thread_id 
  # @option opts [String] :caption 
  # @option opts [String] :parse_mode 
  # @option opts [Array<MessageEntity>] :caption_entities 
  # @option opts [Boolean] :has_spoiler 
  # @option opts [Boolean] :disable_notification 
  # @option opts [Boolean] :protect_content 
  # @option opts [ReplyParameters] :reply_parameters 
  # @option opts [Hash<String, SendMessageReplyMarkupParameterValue>] :reply_markup 
  # @return [SendMessage200Response]
  describe 'send_photo test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for send_poll
  # sendPoll
  # Use this method to send a native poll. On success, the sent Message is returned.
  # @param chat_id 
  # @param question 
  # @param options 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :business_connection_id 
  # @option opts [Integer] :message_thread_id 
  # @option opts [Boolean] :is_anonymous 
  # @option opts [String] :type 
  # @option opts [Boolean] :allows_multiple_answers 
  # @option opts [Integer] :correct_option_id 
  # @option opts [String] :explanation 
  # @option opts [String] :explanation_parse_mode 
  # @option opts [Array<MessageEntity>] :explanation_entities 
  # @option opts [Integer] :open_period 
  # @option opts [Integer] :close_date 
  # @option opts [Boolean] :is_closed 
  # @option opts [Boolean] :disable_notification 
  # @option opts [Boolean] :protect_content 
  # @option opts [ReplyParameters] :reply_parameters 
  # @option opts [Hash<String, SendMessageReplyMarkupParameterValue>] :reply_markup 
  # @return [SendMessage200Response]
  describe 'send_poll test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for send_sticker
  # sendSticker
  # Use this method to send static .WEBP, animated .TGS, or video .WEBM stickers. On success, the sent Message is returned.
  # @param chat_id 
  # @param sticker 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :business_connection_id 
  # @option opts [Integer] :message_thread_id 
  # @option opts [String] :emoji 
  # @option opts [Boolean] :disable_notification 
  # @option opts [Boolean] :protect_content 
  # @option opts [ReplyParameters] :reply_parameters 
  # @option opts [Hash<String, SendMessageReplyMarkupParameterValue>] :reply_markup 
  # @return [SendMessage200Response]
  describe 'send_sticker test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for send_venue
  # sendVenue
  # Use this method to send information about a venue. On success, the sent Message is returned.
  # @param chat_id 
  # @param latitude 
  # @param longitude 
  # @param title 
  # @param address 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :business_connection_id 
  # @option opts [Integer] :message_thread_id 
  # @option opts [String] :foursquare_id 
  # @option opts [String] :foursquare_type 
  # @option opts [String] :google_place_id 
  # @option opts [String] :google_place_type 
  # @option opts [Boolean] :disable_notification 
  # @option opts [Boolean] :protect_content 
  # @option opts [ReplyParameters] :reply_parameters 
  # @option opts [Hash<String, SendMessageReplyMarkupParameterValue>] :reply_markup 
  # @return [SendMessage200Response]
  describe 'send_venue test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for send_video
  # sendVideo
  # Use this method to send video files, Telegram clients support MPEG4 videos (other formats may be sent as Document). On success, the sent Message is returned. Bots can currently send video files of up to 50 MB in size, this limit may be changed in the future.
  # @param chat_id 
  # @param video 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :business_connection_id 
  # @option opts [Integer] :message_thread_id 
  # @option opts [Integer] :duration 
  # @option opts [Integer] :width 
  # @option opts [Integer] :height 
  # @option opts [Hash<String, SendPhotoPhotoParameterValue>] :thumbnail 
  # @option opts [String] :caption 
  # @option opts [String] :parse_mode 
  # @option opts [Array<MessageEntity>] :caption_entities 
  # @option opts [Boolean] :has_spoiler 
  # @option opts [Boolean] :supports_streaming 
  # @option opts [Boolean] :disable_notification 
  # @option opts [Boolean] :protect_content 
  # @option opts [ReplyParameters] :reply_parameters 
  # @option opts [Hash<String, SendMessageReplyMarkupParameterValue>] :reply_markup 
  # @return [SendMessage200Response]
  describe 'send_video test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for send_video_note
  # sendVideoNote
  # As of v.4.0, Telegram clients support rounded square MPEG4 videos of up to 1 minute long. Use this method to send video messages. On success, the sent Message is returned.
  # @param chat_id 
  # @param video_note 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :business_connection_id 
  # @option opts [Integer] :message_thread_id 
  # @option opts [Integer] :duration 
  # @option opts [Integer] :length 
  # @option opts [Hash<String, SendPhotoPhotoParameterValue>] :thumbnail 
  # @option opts [Boolean] :disable_notification 
  # @option opts [Boolean] :protect_content 
  # @option opts [ReplyParameters] :reply_parameters 
  # @option opts [Hash<String, SendMessageReplyMarkupParameterValue>] :reply_markup 
  # @return [SendMessage200Response]
  describe 'send_video_note test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for send_voice
  # sendVoice
  # Use this method to send audio files, if you want Telegram clients to display the file as a playable voice message. For this to work, your audio must be in an .OGG file encoded with OPUS (other formats may be sent as Audio or Document). On success, the sent Message is returned. Bots can currently send voice messages of up to 50 MB in size, this limit may be changed in the future.
  # @param chat_id 
  # @param voice 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :business_connection_id 
  # @option opts [Integer] :message_thread_id 
  # @option opts [String] :caption 
  # @option opts [String] :parse_mode 
  # @option opts [Array<MessageEntity>] :caption_entities 
  # @option opts [Integer] :duration 
  # @option opts [Boolean] :disable_notification 
  # @option opts [Boolean] :protect_content 
  # @option opts [ReplyParameters] :reply_parameters 
  # @option opts [Hash<String, SendMessageReplyMarkupParameterValue>] :reply_markup 
  # @return [SendMessage200Response]
  describe 'send_voice test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for set_chat_administrator_custom_title
  # setChatAdministratorCustomTitle
  # Use this method to set a custom title for an administrator in a supergroup promoted by the bot. Returns True on success.
  # @param chat_id 
  # @param user_id 
  # @param custom_title 
  # @param [Hash] opts the optional parameters
  # @return [SetWebhook200Response]
  describe 'set_chat_administrator_custom_title test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for set_chat_description
  # setChatDescription
  # Use this method to change the description of a group, a supergroup or a channel. The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights. Returns True on success.
  # @param chat_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :description 
  # @return [SetWebhook200Response]
  describe 'set_chat_description test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for set_chat_menu_button
  # setChatMenuButton
  # Use this method to change the bot&#39;s menu button in a private chat, or the default menu button. Returns True on success.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :chat_id 
  # @option opts [Object] :menu_button 
  # @return [SetWebhook200Response]
  describe 'set_chat_menu_button test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for set_chat_permissions
  # setChatPermissions
  # Use this method to set default chat permissions for all members. The bot must be an administrator in the group or a supergroup for this to work and must have the can_restrict_members administrator rights. Returns True on success.
  # @param chat_id 
  # @param permissions 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :use_independent_chat_permissions 
  # @return [SetWebhook200Response]
  describe 'set_chat_permissions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for set_chat_photo
  # setChatPhoto
  # Use this method to set a new profile photo for the chat. Photos can&#39;t be changed for private chats. The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights. Returns True on success.
  # @param chat_id 
  # @param photo 
  # @param [Hash] opts the optional parameters
  # @return [SetWebhook200Response]
  describe 'set_chat_photo test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for set_chat_sticker_set
  # setChatStickerSet
  # Use this method to set a new group sticker set for a supergroup. The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights. Use the field can_set_sticker_set optionally returned in getChat requests to check if the bot can use this method. Returns True on success.
  # @param chat_id 
  # @param sticker_set_name 
  # @param [Hash] opts the optional parameters
  # @return [SetWebhook200Response]
  describe 'set_chat_sticker_set test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for set_chat_title
  # setChatTitle
  # Use this method to change the title of a chat. Titles can&#39;t be changed for private chats. The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights. Returns True on success.
  # @param chat_id 
  # @param title 
  # @param [Hash] opts the optional parameters
  # @return [SetWebhook200Response]
  describe 'set_chat_title test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for set_custom_emoji_sticker_set_thumbnail
  # setCustomEmojiStickerSetThumbnail
  # Use this method to set the thumbnail of a custom emoji sticker set. Returns True on success.
  # @param name 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :custom_emoji_id 
  # @return [SetWebhook200Response]
  describe 'set_custom_emoji_sticker_set_thumbnail test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for set_game_score
  # setGameScore
  # Use this method to set the score of the specified user in a game message. On success, if the message is not an inline message, the Message is returned, otherwise True is returned. Returns an error, if the new score is not greater than the user&#39;s current score in the chat and force is False.
  # @param user_id 
  # @param score 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :force 
  # @option opts [Boolean] :disable_edit_message 
  # @option opts [Integer] :chat_id 
  # @option opts [Integer] :message_id 
  # @option opts [String] :inline_message_id 
  # @return [EditMessageText200Response]
  describe 'set_game_score test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for set_message_reaction
  # setMessageReaction
  # Use this method to change the chosen reactions on a message. Service messages can&#39;t be reacted to. Automatically forwarded messages from a channel to its discussion group have the same available reactions as messages in the channel. Returns True on success.
  # @param chat_id 
  # @param message_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Array<Object>] :reaction 
  # @option opts [Boolean] :is_big 
  # @return [SetWebhook200Response]
  describe 'set_message_reaction test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for set_my_commands
  # setMyCommands
  # Use this method to change the list of the bot&#39;s commands. See this manual for more details about bot commands. Returns True on success.
  # @param commands 
  # @param [Hash] opts the optional parameters
  # @option opts [Object] :scope 
  # @option opts [String] :language_code 
  # @return [SetWebhook200Response]
  describe 'set_my_commands test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for set_my_default_administrator_rights
  # setMyDefaultAdministratorRights
  # Use this method to change the default administrator rights requested by the bot when it&#39;s added as an administrator to groups or channels. These rights will be suggested to users, but they are free to modify the list before adding the bot. Returns True on success.
  # @param [Hash] opts the optional parameters
  # @option opts [ChatAdministratorRights] :rights 
  # @option opts [Boolean] :for_channels 
  # @return [SetWebhook200Response]
  describe 'set_my_default_administrator_rights test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for set_my_description
  # setMyDescription
  # Use this method to change the bot&#39;s description, which is shown in the chat with the bot if the chat is empty. Returns True on success.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :description 
  # @option opts [String] :language_code 
  # @return [SetWebhook200Response]
  describe 'set_my_description test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for set_my_name
  # setMyName
  # Use this method to change the bot&#39;s name. Returns True on success.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :name 
  # @option opts [String] :language_code 
  # @return [SetWebhook200Response]
  describe 'set_my_name test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for set_my_short_description
  # setMyShortDescription
  # Use this method to change the bot&#39;s short description, which is shown on the bot&#39;s profile page and is sent together with the link when users share the bot. Returns True on success.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :short_description 
  # @option opts [String] :language_code 
  # @return [SetWebhook200Response]
  describe 'set_my_short_description test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for set_passport_data_errors
  # setPassportDataErrors
  # Informs a user that some of the Telegram Passport elements they provided contains errors. The user will not be able to re-submit their Passport to you until the errors are fixed (the contents of the field for which you returned the error must change). Returns True on success. Use this if the data submitted by the user doesn&#39;t satisfy the standards your service requires for any reason. For example, if a birthday date seems invalid, a submitted document is blurry, a scan shows evidence of tampering, etc. Supply some details in the error message to make sure the user knows how to correct the issues.
  # @param user_id 
  # @param errors 
  # @param [Hash] opts the optional parameters
  # @return [SetWebhook200Response]
  describe 'set_passport_data_errors test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for set_sticker_emoji_list
  # setStickerEmojiList
  # Use this method to change the list of emoji assigned to a regular or custom emoji sticker. The sticker must belong to a sticker set created by the bot. Returns True on success.
  # @param sticker 
  # @param emoji_list 
  # @param [Hash] opts the optional parameters
  # @return [SetWebhook200Response]
  describe 'set_sticker_emoji_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for set_sticker_keywords
  # setStickerKeywords
  # Use this method to change search keywords assigned to a regular or custom emoji sticker. The sticker must belong to a sticker set created by the bot. Returns True on success.
  # @param sticker 
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :keywords 
  # @return [SetWebhook200Response]
  describe 'set_sticker_keywords test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for set_sticker_mask_position
  # setStickerMaskPosition
  # Use this method to change the mask position of a mask sticker. The sticker must belong to a sticker set that was created by the bot. Returns True on success.
  # @param sticker 
  # @param [Hash] opts the optional parameters
  # @option opts [MaskPosition] :mask_position 
  # @return [SetWebhook200Response]
  describe 'set_sticker_mask_position test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for set_sticker_position_in_set
  # setStickerPositionInSet
  # Use this method to move a sticker in a set created by the bot to a specific position. Returns True on success.
  # @param sticker 
  # @param position 
  # @param [Hash] opts the optional parameters
  # @return [SetWebhook200Response]
  describe 'set_sticker_position_in_set test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for set_sticker_set_thumbnail
  # setStickerSetThumbnail
  # Use this method to set the thumbnail of a regular or mask sticker set. The format of the thumbnail file must match the format of the stickers in the set. Returns True on success.
  # @param name 
  # @param user_id 
  # @param format 
  # @param [Hash] opts the optional parameters
  # @option opts [Hash<String, SendPhotoPhotoParameterValue>] :thumbnail 
  # @return [SetWebhook200Response]
  describe 'set_sticker_set_thumbnail test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for set_sticker_set_title
  # setStickerSetTitle
  # Use this method to set the title of a created sticker set. Returns True on success.
  # @param name 
  # @param title 
  # @param [Hash] opts the optional parameters
  # @return [SetWebhook200Response]
  describe 'set_sticker_set_title test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for set_webhook
  # setWebhook
  # Use this method to specify a URL and receive incoming updates via an outgoing webhook. Whenever there is an update for the bot, we will send an HTTPS POST request to the specified URL, containing a JSON-serialized Update. In case of an unsuccessful request, we will give up after a reasonable amount of attempts. Returns True on success. If you&#39;d like to make sure that the webhook was set by you, you can specify secret data in the parameter secret_token. If specified, the request will contain a header \&quot;X-Telegram-Bot-Api-Secret-Token\&quot; with the secret token as content.
  # @param url 
  # @param [Hash] opts the optional parameters
  # @option opts [Object] :certificate 
  # @option opts [String] :ip_address 
  # @option opts [Integer] :max_connections 
  # @option opts [Array<String>] :allowed_updates 
  # @option opts [Boolean] :drop_pending_updates 
  # @option opts [String] :secret_token 
  # @return [SetWebhook200Response]
  describe 'set_webhook test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for stop_message_live_location
  # stopMessageLiveLocation
  # Use this method to stop updating a live location message before live_period expires. On success, if the message is not an inline message, the edited Message is returned, otherwise True is returned.
  # @param [Hash] opts the optional parameters
  # @option opts [Hash<String, SendMessageChatIdParameterValue>] :chat_id 
  # @option opts [Integer] :message_id 
  # @option opts [String] :inline_message_id 
  # @option opts [InlineKeyboardMarkup] :reply_markup 
  # @return [EditMessageText200Response]
  describe 'stop_message_live_location test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for stop_poll
  # stopPoll
  # Use this method to stop a poll which was sent by the bot. On success, the stopped Poll is returned.
  # @param chat_id 
  # @param message_id 
  # @param [Hash] opts the optional parameters
  # @option opts [InlineKeyboardMarkup] :reply_markup 
  # @return [StopPoll200Response]
  describe 'stop_poll test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for unban_chat_member
  # unbanChatMember
  # Use this method to unban a previously banned user in a supergroup or channel. The user will not return to the group or channel automatically, but will be able to join via link, etc. The bot must be an administrator for this to work. By default, this method guarantees that after the call the user is not a member of the chat, but will be able to join it. So if the user is a member of the chat they will also be removed from the chat. If you don&#39;t want this, use the parameter only_if_banned. Returns True on success.
  # @param chat_id 
  # @param user_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :only_if_banned 
  # @return [SetWebhook200Response]
  describe 'unban_chat_member test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for unban_chat_sender_chat
  # unbanChatSenderChat
  # Use this method to unban a previously banned channel chat in a supergroup or channel. The bot must be an administrator for this to work and must have the appropriate administrator rights. Returns True on success.
  # @param chat_id 
  # @param sender_chat_id 
  # @param [Hash] opts the optional parameters
  # @return [SetWebhook200Response]
  describe 'unban_chat_sender_chat test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for unhide_general_forum_topic
  # unhideGeneralForumTopic
  # Use this method to unhide the &#39;General&#39; topic in a forum supergroup chat. The bot must be an administrator in the chat for this to work and must have the can_manage_topics administrator rights. Returns True on success.
  # @param chat_id 
  # @param [Hash] opts the optional parameters
  # @return [SetWebhook200Response]
  describe 'unhide_general_forum_topic test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for unpin_all_chat_messages
  # unpinAllChatMessages
  # Use this method to clear the list of pinned messages in a chat. If the chat is not a private chat, the bot must be an administrator in the chat for this to work and must have the &#39;can_pin_messages&#39; administrator right in a supergroup or &#39;can_edit_messages&#39; administrator right in a channel. Returns True on success.
  # @param chat_id 
  # @param [Hash] opts the optional parameters
  # @return [SetWebhook200Response]
  describe 'unpin_all_chat_messages test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for unpin_all_forum_topic_messages
  # unpinAllForumTopicMessages
  # Use this method to clear the list of pinned messages in a forum topic. The bot must be an administrator in the chat for this to work and must have the can_pin_messages administrator right in the supergroup. Returns True on success.
  # @param chat_id 
  # @param message_thread_id 
  # @param [Hash] opts the optional parameters
  # @return [SetWebhook200Response]
  describe 'unpin_all_forum_topic_messages test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for unpin_all_general_forum_topic_messages
  # unpinAllGeneralForumTopicMessages
  # Use this method to clear the list of pinned messages in a General forum topic. The bot must be an administrator in the chat for this to work and must have the can_pin_messages administrator right in the supergroup. Returns True on success.
  # @param chat_id 
  # @param [Hash] opts the optional parameters
  # @return [SetWebhook200Response]
  describe 'unpin_all_general_forum_topic_messages test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for unpin_chat_message
  # unpinChatMessage
  # Use this method to remove a message from the list of pinned messages in a chat. If the chat is not a private chat, the bot must be an administrator in the chat for this to work and must have the &#39;can_pin_messages&#39; administrator right in a supergroup or &#39;can_edit_messages&#39; administrator right in a channel. Returns True on success.
  # @param chat_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :message_id 
  # @return [SetWebhook200Response]
  describe 'unpin_chat_message test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for upload_sticker_file
  # uploadStickerFile
  # Use this method to upload a file with a sticker for later use in the createNewStickerSet, addStickerToSet, or replaceStickerInSet methods (the file can be used multiple times). Returns the uploaded File on success.
  # @param user_id 
  # @param sticker 
  # @param sticker_format 
  # @param [Hash] opts the optional parameters
  # @return [GetFile200Response]
  describe 'upload_sticker_file test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
