=begin
#telegram-bot-api

#Unofficial telegram-bot-api OpenAPI spec. Generated from the Bot API docs at https://core.telegram.org/bots/api

The version of the OpenAPI document: Bot API 7.2

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TelegramBotOpenapi::InputSticker
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TelegramBotOpenapi::InputSticker do
  let(:instance) { TelegramBotOpenapi::InputSticker.new }

  describe 'test an instance of InputSticker' do
    it 'should create an instance of InputSticker' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(TelegramBotOpenapi::InputSticker)
    end
  end

  describe 'test attribute "sticker"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "format"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "emoji_list"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "mask_position"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "keywords"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
