=begin
#telegram-bot-api

#Unofficial telegram-bot-api OpenAPI spec. Generated from the Bot API docs at https://core.telegram.org/bots/api

The version of the OpenAPI document: Bot API 7.2

Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TelegramBotOpenapi::ReplyKeyboardMarkup
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TelegramBotOpenapi::ReplyKeyboardMarkup do
  let(:instance) { TelegramBotOpenapi::ReplyKeyboardMarkup.new }

  describe 'test an instance of ReplyKeyboardMarkup' do
    it 'should create an instance of ReplyKeyboardMarkup' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(TelegramBotOpenapi::ReplyKeyboardMarkup)
    end
  end

  describe 'test attribute "keyboard"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "is_persistent"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "resize_keyboard"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "one_time_keyboard"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "input_field_placeholder"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "selective"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
